"""Filesystem side of the HTML send report: a JSONL recorder and the renderer.

The split mirrors the rest of the codebase — :mod:`sender.domain.reporting` turns
data into HTML text, and this module owns paths, locking, retention and the
Apache config that keeps the report off the open web.

Two artifacts live under the configured report directory:

``data/<date>.jsonl``
    The append-only source of truth, one JSON object per send attempt. Pages are
    *regenerated* from it, so a bug in the renderer is fixable without losing
    history, and a failed regeneration cannot destroy yesterday's report.

``<date>.html`` + ``index.html``
    The browsable view.

The JSONL is the record; the HTML is a rendering of it.
"""

from __future__ import annotations

import json
import logging
import os
import re
from datetime import date, timedelta
from pathlib import Path
from typing import Iterable, Sequence

from sender.domain.models import SendOutcome
from sender.domain.reporting import (
    outcome_from_json,
    outcome_to_json,
    render_date_page,
    render_index,
    render_recipients,
)
from sender.infrastructure.util import write_text_atomic

log = logging.getLogger(__name__)

_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})\.jsonl$")

#: Delimiters of the generated region in the report root's .htaccess. The
#: renderer rewrites everything between them on every run; anything outside them
#: is operator-owned and preserved, so a hand-added basic-auth block survives the
#: five-minute cron cycle that re-renders the report.
_HTACCESS_BEGIN = "# BEGIN Aizen invoice sender generated block"
_HTACCESS_END = "# END Aizen invoice sender generated block"

#: Written into the report root so the raw JSONL cannot be fetched directly and
#: the directory cannot be listed. The pages themselves are not protected — the
#: report directory is expected to sit behind .htpasswd or outside the docroot
#: (see docs/guide/reporting.md); this only closes the two easy doors.
_GENERATED_HTACCESS = """Options -Indexes

# The raw send log is the source of truth, not something to browse.
<FilesMatch "\\.jsonl$">
    Require all denied
</FilesMatch>

# Matched against the path as it appears in the request. The report root is
# served at /reports, so the bare ^/data/ form would not match the JSONL's real
# location and has to be anchored to whatever directory this file sits in.
RedirectMatch 404 ^/(.*/)?data/
"""

#: The whole-file .htaccess older versions wrote. Recognised only so the first
#: render after an upgrade replaces it instead of duplicating every directive.
_LEGACY_HTACCESS = (
    "# Generated by the Aizen invoice sender. Do not edit by hand.\n"
    + _GENERATED_HTACCESS.replace(
        "# Matched against the path as it appears in the request. The report root\n"
        "# is served at /reports, so the bare ^/data/ form would not match the\n"
        "# JSONL's real location and has to be anchored to whatever directory this\n"
        "# file sits in.\n",
        "",
    ).replace("RedirectMatch 404 ^/(.*/)?data/", "RedirectMatch 404 ^/data/")
)


def merge_htaccess(existing: str) -> str:
    """Merge the generated region into an existing .htaccess file.

    The generated directives live between two marker comments; everything
    outside them is operator-owned and returned untouched. A file written
    before the markers existed is recognised and replaced wholesale, so the
    first render after an upgrade does not duplicate every directive.
    """
    region = f"{_HTACCESS_BEGIN}\n{_GENERATED_HTACCESS}{_HTACCESS_END}\n"
    begin = existing.find(_HTACCESS_BEGIN)
    end = existing.find(_HTACCESS_END)
    if begin != -1 and end != -1 and begin < end:
        tail = existing[end + len(_HTACCESS_END):]
        if tail.startswith("\n"):
            # The region ends with its own newline; without dropping the old
            # file's trailing one, every render would grow the file by a line.
            tail = tail[1:]
        return existing[:begin] + region + tail
    if existing.startswith(_LEGACY_HTACCESS):
        existing = existing[len(_LEGACY_HTACCESS):]
    return region + existing


def _local_day(epoch: float) -> date:
    """The host-local date of an epoch timestamp.

    Local time is deliberate and matches how the poll summary prints
    timestamps: the operator reads "what happened today" against the host's
    clock, so the day boundary is the server's, not UTC's.
    """
    from datetime import datetime

    try:
        return datetime.fromtimestamp(epoch).date()
    except (OverflowError, OSError, ValueError):
        return date.today()


class JsonlSendOutcomeRecorder:
    """Append send outcomes to ``<data_dir>/<date>.jsonl``.

    Best-effort by design, and this is a deliberate departure from the poll
    state store's "never swallow a write failure" contract. The state store is
    load-bearing — losing a write there means re-sending an invoice — whereas
    the report is an observability artifact. If the report directory is
    unwritable, the correct behaviour is to log loudly and keep sending, not to
    fail a cycle that has already put messages in front of customers.

    Each line is written with a single ``O_APPEND`` write, which POSIX makes
    atomic for writes below ``PIPE_BUF``, so a concurrent appender cannot
    interleave a partial line.
    """

    def __init__(self, data_dir: str | os.PathLike[str]) -> None:
        self._dir = Path(data_dir)
        self.dates_written: set[date] = set()

    def record(self, outcome: SendOutcome) -> None:
        line = json.dumps(outcome_to_json(outcome), ensure_ascii=False) + "\n"
        day = _local_day(outcome.attempted_at)
        path = self._dir / f"{day.isoformat()}.jsonl"
        try:
            self._dir.mkdir(parents=True, exist_ok=True)
            fd = os.open(path, os.O_WRONLY | os.O_APPEND | os.O_CREAT, 0o600)
            try:
                os.write(fd, line.encode("utf-8"))
            finally:
                os.close(fd)
            self.dates_written.add(day)
        except OSError:
            # Swallowed on purpose: see the class docstring.
            log.exception("could not append the send outcome for invoice %s", outcome.invoice_id)


class ReportStore:
    """Regenerate the HTML pages from the JSONL log and apply retention."""

    def __init__(
        self,
        report_dir: str | os.PathLike[str],
        data_dir: str | os.PathLike[str],
        *,
        obfuscate: bool = True,
    ) -> None:
        self._report_dir = Path(report_dir)
        self._data_dir = Path(data_dir)
        self._obfuscate = obfuscate

    def available_dates(self) -> list[date]:
        """Dates that have a JSONL log, newest first."""
        return sorted(self._dates(), reverse=True)

    def _dates(self) -> set[date]:
        found: set[date] = set()
        if not self._data_dir.is_dir():
            return found
        for path in self._data_dir.glob("*.jsonl"):
            match = _DATE_RE.match(path.name)
            if not match:
                continue
            try:
                found.add(date.fromisoformat(match.group(1)))
            except ValueError:
                continue
        return found

    def load(self, day: date) -> list[SendOutcome]:
        """Read one day's outcomes, skipping lines that cannot be parsed."""
        path = self._data_dir / f"{day.isoformat()}.jsonl"
        if not path.is_file():
            return []
        entries: list[SendOutcome] = []
        try:
            with open(path, encoding="utf-8") as handle:
                for line in handle:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entries.append(outcome_from_json(json.loads(line)))
                    except (ValueError, TypeError):
                        # One bad historical line costs one row, not the report.
                        log.warning("skipping malformed report line in %s", path.name)
        except OSError:
            log.exception("could not read the report log for %s", day.isoformat())
        return entries

    def render(self, days: Iterable[date] | None = None, *, index: bool = True) -> list[Path]:
        """Write the dated pages, the index and the .htaccess.

        Returns the files written. Idempotent: regeneration from the same log
        produces the same bytes, so a manual run racing the end of a poll cycle
        is harmless last-writer-wins.

        The ``.htaccess`` is merged rather than replaced. Only the
        marker-delimited region is rewritten, so auth directives an operator
        added outside it survive the next cron cycle.
        """
        targets = sorted(set(days)) if days is not None else self.available_dates()
        written: list[Path] = []
        counts: dict[date, tuple[int, int]] = {}

        self._report_dir.mkdir(parents=True, exist_ok=True)
        for day in targets:
            entries = self.load(day)
            counts[day] = (
                sum(1 for item in entries if item.ok),
                sum(1 for item in entries if not item.ok),
            )
            page = self._report_dir / f"{day.isoformat()}.html"
            write_text_atomic(page, render_date_page(day, entries, obfuscate=self._obfuscate))
            written.append(page)

        if index:
            index_path = self._report_dir / "index.html"
            write_text_atomic(
                index_path,
                render_index(self._dates(), counts),
            )
            written.append(index_path)

            recipients_path = self._report_dir / "recipients.html"
            write_text_atomic(
                recipients_path,
                render_recipients(self._all_entries(), obfuscate=self._obfuscate),
            )
            written.append(recipients_path)

        htaccess = self._report_dir / ".htaccess"
        existing = htaccess.read_text(encoding="utf-8") if htaccess.exists() else ""
        write_text_atomic(htaccess, merge_htaccess(existing))
        written.append(htaccess)
        return written

    def _all_entries(self) -> list[SendOutcome]:
        """Every logged outcome, oldest first, for the recipients page.

        Read back from the JSONL rather than kept in memory: a cron ``--once``
        run has no shared process state, so the log on disk is the only source
        that spans cycles.
        """
        entries: list[SendOutcome] = []
        for day in self.available_dates():
            entries.extend(self.load(day))
        entries.sort(key=lambda item: item.attempted_at)
        return entries

    def prune(self, retention_days: int) -> list[date]:
        """Delete logs and pages older than *retention_days*.

        ``retention_days <= 0`` disables pruning. Only files the store owns are
        touched: a date-shaped JSONL and the matching HTML page.
        """
        if retention_days <= 0:
            return []
        cutoff = date.today() - timedelta(days=retention_days)
        removed: list[date] = []
        for day in sorted(self._dates()):
            if day >= cutoff:
                continue
            for path in (
                self._data_dir / f"{day.isoformat()}.jsonl",
                self._report_dir / f"{day.isoformat()}.html",
            ):
                try:
                    path.unlink(missing_ok=True)
                except OSError:
                    log.exception("could not remove the expired report %s", path.name)
                    continue
            removed.append(day)
        if removed:
            log.info("pruned %d expired report day(s) older than %s", len(removed), cutoff)
        return removed